### ISSUE TITLE
Sublime Babel

### ISSUE THREAD

**Issue by Method-X** [mgmcdermott/vscode-language-babel#1]
What's the difference between this and [Sublime Babel](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode)?

**Comment by mgmcdermott** [comment]
In regular JavaScript, there are only subtle differences (import/export statements and function calls), however the real difference is that this package has improved Flow support as well as syntax highlighting for GraphQL and styled-components. While Sublime Babel supports React and JSX pretty well, I personally prefer the highlighting provided by this package (mainly that JSX components are treated the same as classes).

It's all obviously a matter of preference and this is mine!

Sublime Babel:
<img width="375" alt="screen shot 2017-06-12 at 10 14 02 pm" src="https://user-images.githubusercontent.com/8161781/27062952-ad0db96e-4fbc-11e7-8b14-d99dee2529fd.png">

Babel JavaScript:
<img width="381" alt="screen shot 2017-06-12 at 10 17 15 pm" src="https://user-images.githubusercontent.com/8161781/27062994-f8346096-4fbc-11e7-90a2-5910e1fc8cbb.png">

Sublime Babel:
<img width="247" alt="screen shot 2017-06-12 at 10 10 51 pm" src="https://user-images.githubusercontent.com/8161781/27062878-377d926e-4fbc-11e7-930b-804d48a15b92.png">
Babel JavaScript:
<img width="481" alt="screen shot 2017-06-12 at 10 10 15 pm" src="https://user-images.githubusercontent.com/8161781/27062887-465eeaf8-4fbc-11e7-94d1-4de16c76aaeb.png">

Sublime Babel:
<img width="574" alt="screen shot 2017-06-12 at 10 11 40 pm" src="https://user-images.githubusercontent.com/8161781/27062893-5373fd8c-4fbc-11e7-8d67-299af1611563.png">
<img width="393" alt="screen shot 2017-06-12 at 10 13 23 pm" src="https://user-images.githubusercontent.com/8161781/27062898-5fb08c3c-4fbc-11e7-8654-e4b7348d1c0b.png">
Babel JavaScript:
<img width="555" alt="screen shot 2017-06-12 at 10 09 37 pm" src="https://user-images.githubusercontent.com/8161781/27062926-8c0c2c96-4fbc-11e7-8051-11d3df5e919f.png">

Sublime Babel:
<img width="525" alt="screen shot 2017-06-12 at 10 16 07 pm" src="https://user-images.githubusercontent.com/8161781/27062961-c7b10d48-4fbc-11e7-82af-1f3909916d20.png">
Babel JavaScript:
<img width="531" alt="screen shot 2017-06-12 at 10 08 55 pm" src="https://user-images.githubusercontent.com/8161781/27062996-fc3dbfe8-4fbc-11e7-9fec-7784ca7af6b7.png">

**Comment by Method-X** [comment]
@mgmcdermott Thanks for the detailed response. I respect your attention to detail and I'm definitely giving it a try!

**Comment by xDae** [comment]
also comment that in this package commenting inside JSX works better than in sublime babel

Sublime babel comments JSX with ``//``
this package comments JSX in the correct way with ``{** *}``

**Comment by kurtextrem** [comment]
Regarding the screenshots:
The import screenshots seem switched - the first screenshot shows Babel JavaScript, the second Sublime Babel.

Regarding the JSX Tags:
I can't see why the Babel JavaScript color should be correct. Open an HTML file, write a few tags. They're not yellow, they're red. Hence, the JSX tags should be red as well (like Sublime Babel).

**Comment by michaelgmcd** [comment]
All screenshots were taken using the "Theme - Oceanic Next" theme.

**Comment by michaelgmcd** [comment]
Regarding your second point, valid html tags (input, p, span, h1, etc) will be red just like html. Components (with a capital letter) are NOT valid html and hence they are colored like the classes that they are.

**Comment by kurtextrem** [comment]
I see, that makes sense. Had not noticed that (subtle but important) difference :)

**Comment by irishabh96** [comment]
what is the name of the font you are using ?

**Comment by rattrayalex-stripe** [comment]
Sorry, can you provide screenshots for any differences in flow-types as well?

**Comment by hamzashahab1610** [comment]
can you please tell me what font is this??

**Comment by xxczaki** [comment]
@hamzashahab1610 I guess it is Operator Mono

**Comment by FredWolfe** [comment]
> also comment that in this package commenting inside JSX works better than in sublime babel
> 
> Sublime babel comments JSX with `// xxx` this package comments JSX in the correct way with `{/* xxx */}`

what is the shortcut to doing this type of commenting in vscode

**Comment by FredWolfe** [comment]
> also comment that in this package commenting inside JSX works better than in sublime babel
> 
> Sublime babel comments JSX with `// xxx` this package comments JSX in the correct way with `{/* xxx */}`

what is the shortcut to doing this type of commenting in vscode
